{
  "report": {
    "environment": {
      "Platform": "Darwin-15.3.0-x86_64-i386-64bit",
      "Python": "3.5.2"
    },
    "summary": {
      "duration": 3234.79989897,
      "num_tests": 10,
      "failed": 6,
      "skipped": 1,
      "passed": 3
    },
    "created_at": "2016-12-09 20:48:17.916771",
    "tests": [
      {
        "call": {
          "duration": 0.4680900573730469,
          "name": "call",
          "longrepr": "self = <api.tests.test_api_home_page.HomePageAPITests testMethod=test_user_can_not_filter_with_non_existing_cdt_id>\n\n    @pytest.mark.home_page_api\n    def test_user_can_not_filter_with_non_existing_cdt_id(self):\n        filter_cdt_id = \"99999999\"\n        response = self.opportunity_api_client.get_filtered_opportunities(cdt_id=filter_cdt_id)\n        self.assertEquals(400, response.status_code, msg=\"The response code returned does not match expected value.\"\n                                                         \"Expected: {0}\"\n>                                                        \"Actual: {1}\".format(400, response.status_code))\nE       AssertionError: 400 != 200 : The response code returned does not match expected value.Expected: 400Actual: 200\n\napi/tests/test_api_home_page.py:63: AssertionError",
          "outcome": "failed"
        },
        "teardown": {
          "duration": 0.00010704994201660156,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_not_filter_with_non_existing_cdt_id",
        "run_index": 8,
        "setup": {
          "duration": 0.0003159046173095703,
          "name": "setup",
          "outcome": "passed"
        },
        "duration": 0.4688289165496826,
        "outcome": "failed"
      },
      {
        "call": {
          "duration": 1.5519399642944336,
          "name": "call",
          "outcome": "passed"
        },
        "teardown": {
          "duration": 0.00007700920104980469,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_delete_an_opportunity",
        "run_index": 1,
        "setup": {
          "duration": 0.0003681182861328125,
          "name": "setup",
          "outcome": "passed"
        },
        "duration": 1.552753210067749,
        "outcome": "passed"
      },
      {
        "call": {
          "duration": 1.8568809032440186,
          "name": "call",
          "longrepr": "self = <api.tests.test_api_home_page.HomePageAPITests testMethod=test_user_can_not_create_a_new_opportunity_with_invalid_cdt_type>\n\n    @pytest.mark.home_page_api\n    def test_user_can_not_create_a_new_opportunity_with_invalid_cdt_type(self):\n        cdt_type = \"abcd\"\n        opportunity_type = \"MANUAL\"\n        opportunity_name = \"api_created_opportunity_{0}\".format(random.randint(1, 100))\n        response = self.opportunity_api_client.create_opportunity(cdt_type, opportunity_type, opportunity_name)\n        self.assertEquals(400, response.status_code, msg=\"The response code returned does not match expected value.\"\n                                                         \"Expected: {0}\"\n>                                                        \"Actual: {1}\".format(400, response.status_code))\nE       AssertionError: 400 != 500 : The response code returned does not match expected value.Expected: 400Actual: 500\n\napi/tests/test_api_home_page.py:106: AssertionError",
          "outcome": "failed"
        },
        "teardown": {
          "duration": 0.00008916854858398438,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_not_create_a_new_opportunity_with_invalid_cdt_type",
        "run_index": 3,
        "setup": {
          "duration": 0.0003139972686767578,
          "name": "setup",
          "outcome": "passed"
        },
        "duration": 1.857598066329956,
        "outcome": "failed"
      },
      {
        "call": {
          "duration": 0.7198469638824463,
          "name": "call",
          "longrepr": "self = <api.tests.test_api_home_page.HomePageAPITests testMethod=test_user_can_not_delete_an_opportunity_with_nonexistent_id>\n\n    @pytest.mark.home_page_api\n    def test_user_can_not_delete_an_opportunity_with_nonexistent_id(self):\n        delete_opp = self.opportunity_api_client.delete_opportunity([9999])\n        self.assertEquals(404, delete_opp.status_code, msg=\"The response code returned does not match expected value.\"\n                                                         \"Expected: {0}\"\n>                                                        \"Actual: {1}\".format(404, delete_opp.status_code))\nE       AssertionError: 404 != 200 : The response code returned does not match expected value.Expected: 404Actual: 200\n\napi/tests/test_api_home_page.py:156: AssertionError",
          "outcome": "failed"
        },
        "teardown": {
          "duration": 0.00008106231689453125,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_not_delete_an_opportunity_with_nonexistent_id",
        "run_index": 6,
        "setup": {
          "duration": 0.00024008750915527344,
          "name": "setup",
          "outcome": "passed"
        },
        "duration": 0.7204082012176514,
        "outcome": "failed"
      },
      {
        "call": {
          "duration": 10.704282999038696,
          "name": "call",
          "longrepr": "self = <api.tests.test_api_home_page.HomePageAPITests testMethod=test_user_can_not_create_a_new_opportunity_with_blank_name>\n\n    @pytest.mark.home_page_api\n    def test_user_can_not_create_a_new_opportunity_with_blank_name(self):\n        cdt_type = \"1\"\n        opportunity_type = \"MANUAL\"\n        opportunity_name = \"\"\n        response = self.opportunity_api_client.create_opportunity(cdt_type, opportunity_type, opportunity_name)\n        self.assertEquals(400, response.status_code, msg=\"The response code returned does not match expected value.\"\n                                                         \"Expected: {0}\"\n>                                                        \"Actual: {1}\".format(400, response.status_code))\nE       AssertionError: 400 != 200 : The response code returned does not match expected value.Expected: 400Actual: 200\n\napi/tests/test_api_home_page.py:126: AssertionError",
          "outcome": "failed"
        },
        "teardown": {
          "duration": 0.00009012222290039062,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_not_create_a_new_opportunity_with_blank_name",
        "run_index": 2,
        "setup": {
          "duration": 0.0002789497375488281,
          "name": "setup",
          "outcome": "passed"
        },
        "duration": 10.704931020736694,
        "outcome": "failed"
      },
      {
        "call": {
          "duration": 0.46416807174682617,
          "name": "call",
          "longrepr": "self = <api.tests.test_api_home_page.HomePageAPITests testMethod=test_user_can_not_filter_with_invalid_cdt_id>\n\n    @pytest.mark.home_page_api\n    def test_user_can_not_filter_with_invalid_cdt_id(self):\n        filter_cdt_id = \"abcd%dcf\"\n        response = self.opportunity_api_client.get_filtered_opportunities(cdt_id=filter_cdt_id)\n        self.assertEquals(400, response.status_code, msg=\"The response code returned does not match expected value.\"\n                                                         \"Expected: {0}\"\n>                                                        \"Actual: {1}\".format(400, response.status_code))\nE       AssertionError: 400 != 200 : The response code returned does not match expected value.Expected: 400Actual: 200\n\napi/tests/test_api_home_page.py:55: AssertionError",
          "outcome": "failed"
        },
        "teardown": {
          "duration": 0.00010895729064941406,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_not_filter_with_invalid_cdt_id",
        "run_index": 7,
        "setup": {
          "duration": 0.0002589225769042969,
          "name": "setup",
          "outcome": "passed"
        },
        "duration": 0.4647948741912842,
        "outcome": "failed"
      },
      {
        "call": {
          "duration": 11.64627194404602,
          "name": "call",
          "outcome": "passed"
        },
        "teardown": {
          "duration": 0.00024819374084472656,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_retrieve_all_opportunities",
        "run_index": 9,
        "setup": {
          "duration": 0.00028586387634277344,
          "name": "setup",
          "outcome": "passed"
        },
        "duration": 11.64709186553955,
        "outcome": "passed"
      },
      {
        "call": {
          "duration": 12.255005836486816,
          "name": "call",
          "outcome": "passed"
        },
        "teardown": {
          "duration": 0.00011301040649414062,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_create_a_new_opportunity",
        "run_index": 0,
        "setup": {
          "duration": 0.018386125564575195,
          "name": "setup",
          "outcome": "passed"
        },
        "duration": 12.291891098022461,
        "outcome": "passed"
      },
      {
        "call": {
          "duration": 14.656501770019531,
          "name": "call",
          "longrepr": "self = <api.tests.test_api_home_page.HomePageAPITests testMethod=test_user_can_not_create_a_new_opportunity_with_invalid_opportunity_type>\n\n    @pytest.mark.home_page_api\n    def test_user_can_not_create_a_new_opportunity_with_invalid_opportunity_type(self):\n        cdt_type = \"1\"\n        opportunity_type = \"abcd\"\n        opportunity_name = \"api_created_opportunity_{0}\".format(random.randint(1, 100))\n        response = self.opportunity_api_client.create_opportunity(cdt_type, opportunity_type, opportunity_name)\n        self.assertEquals(400, response.status_code, msg=\"The response code returned does not match expected value.\"\n                                                         \"Expected: {0}\"\n>                                                        \"Actual: {1}\".format(400, response.status_code))\nE       AssertionError: 400 != 500 : The response code returned does not match expected value.Expected: 400Actual: 500\n\napi/tests/test_api_home_page.py:116: AssertionError",
          "outcome": "failed"
        },
        "teardown": {
          "duration": 0.00010180473327636719,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_not_create_a_new_opportunity_with_invalid_opportunity_type",
        "run_index": 4,
        "setup": {
          "duration": 0.00022721290588378906,
          "name": "setup",
          "outcome": "passed"
        },
        "duration": 14.657058000564575,
        "outcome": "failed"
      },
      {
        "teardown": {
          "duration": 0.00008106231689453125,
          "name": "teardown",
          "outcome": "passed"
        },
        "name": "api/tests/test_api_home_page.py::HomePageAPITests::test_user_can_not_delete_an_opportunity_with_invalid_id",
        "run_index": 5,
        "setup": {
          "duration": 0.00009989738464355469,
          "name": "setup",
          "longrepr": "('api/tests/test_api_home_page.py', 142, 'Skipped: no way of currently testing this')",
          "outcome": "skipped"
        },
        "duration": 0.0002808570861816406,
        "outcome": "skipped"
      }
    ]
  }
}
